# Generated by Django 3.2.5 on 2022-09-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO profiles_profile (
                    id,
                    user_id,
                    favorite_city
                )
                SELECT
                    id,
                    user_id,
                    favorite_city
                FROM
                    oc_lettings_site_profile;
            """,
            reverse_sql="""
                INSERT INTO oc_lettings_site_profile (
                    id,
                    user_id,
                    favorite_city
                )
                SELECT
                    id,
                    user_id,
                    favorite_city
                FROM
                    profiles_profile;
            """,
        )
    ]
