# Generated by Django 3.2.5 on 2022-09-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_alter_letting_address'),
    ]

    operations = [
        migrations.RunSQL("""
                INSERT INTO lettings_letting (
                    id,
                    title,
                    address
                )
                SELECT
                    id,
                    title,
                    address
                FROM
                    oc_lettings_site_letting;
            """, reverse_sql="""
                INSERT INTO oc_lettings_site_letting (
                    id,
                    title,
                    address
                )
                SELECT
                    id,
                    title,
                    address
                FROM
                    lettings_letting;
            """)
    ]
