# Generated by Django 3.2.5 on 2022-09-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0003_auto_20220918_1105"),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO lettings_letting (
                    id,
                    title,
                    address_id
                )
                SELECT
                    id,
                    title,
                    address_id
                FROM
                    oc_lettings_site_letting;
            """,
            reverse_sql="""
                INSERT INTO oc_lettings_site_letting (
                    id,
                    title,
                    address_id
                )
                SELECT
                    id,
                    title,
                    address_id
                FROM
                    lettings_letting;
            """,
        )
    ]
