version: 2.1

# Define the jobs we want to run for this project
orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.1
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: cimg/base:2022.06
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:  |
          docker build -t guillaumeferreira/web:$CIRCLE_SHA1 .
          docker push guillaumeferreira/web:$CIRCLE_SHA1
  test:
    docker:
      - image: cimg/python:3.9.6
    resource_class: small
    steps:
      - checkout
      - run:
          name: install packages
          command: |
            pip install --user --no-cache-dir -r requirements.txt
      - run:
          name: run pytest
          command: |
            pytest
      - run:
          name: check linting
          command: |
            flake8

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
