version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/python:3.9.6
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

  build_docker_image:
    docker:
      - image: cimg/python:3.10
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - docker/check
      - docker/build:
          image: ${DOCKER_LOGIN}/web
          tag: $CIRCLE_SHA1

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      - build_docker_image