version: 2.1

# Define the jobs we want to run for this project
orbs:
  python: circleci/python@2.0.1
  docker: circleci/docker@2.0.2
jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/python:3.9.6
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

  build_docker_image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/web
          tag: $CIRCLE_SHA1

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      - build_docker_image