# Generated by Django 3.2.5 on 2022-09-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'address'},
        ),
        migrations.AlterField(
            model_name='letting',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='++', to='oc_lettings_site.address'),
        ),
    ]
